services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped