worker_processes  auto;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
    use epoll;
}

http {
    log_format gmt3  '[$time_local] $request from $remote_addr.'
                     'Response: $status ';
    access_log /var/log/nginx/access.log gmt3;
    error_log  /var/log/nginx/error.log warn;
    
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    types_hash_max_size 2048;

    server_tokens off;
    autoindex off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # 1MB can hold ~ 4000 sessions
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout 1h;
    ssl_session_tickets off;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    gzip on;
    # Add Vary: Accept-Encoding header
	gzip_vary on;
    # Compress requests with "Via" headers, as we're Cloudflared, should be any
	gzip_proxied any;
    # Should be good enough without spiking CPU
	gzip_comp_level 2;
    # Allocates memory for the compression: 16 x 8k = 128KB
	gzip_buffers 16 8k;
    # For backwards-compatibility, someone might be using HTTP 1.0, so don't gzip it
	gzip_http_version 1.1;
	gzip_types 
        text/plain 
        text/css 
        application/json 
        application/javascript 
        text/xml 
        application/xml 
        application/xml+rss 
        text/javascript;
    
    http2 on;    
    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;
}
