name: Nanocalc build and test suite

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Set up web apps mocks
      working-directory: ./backend
      run: |
        cp mocks/fret_calc_mock.py fret_calc.py
        cp mocks/plq_sim_mock.py plq_sim.py
        cp mocks/ri_calc_mock.py ri_calc.py
        cp mocks/tmm_sim_mock.py tmm_sim.py 

    - name: Install project dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install test dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt

    - name: Create necessary directories
      working-directory: ./backend
      run: |
        mkdir -p ./app/upload/fretcalc/result \
                 ./app/upload/ricalc/result \
                 ./app/upload/plqsim/result \
                 ./app/upload/tmmsim/result

  backend-tests:
    runs-on: ubuntu-latest
    needs: backend-build
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Start Flask server in debug mode
      working-directory: ./backend
      run: |
        export UPLOAD_FOLDER='./app/upload'
        export DEBUG=True
        export PORT=8080
        python flaskapp.py &
        sleep 5

    - name: Run unit tests
      working-directory: ./backend
      run: |
        python test_unit_nanocalc.py

    - name: Run end to end tests
      working-directory: ./backend
      run: | 
        python test_e2e_nanocalc.py

    - name: Clean up
      run: |
        killall python
  
  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Cache npm packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-node-

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install
    
    - name: Build production bundle
      working-directory: ./frontend
      run: npm run build
